### ISSUE TITLE
dev -> main

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReNodes#64]
- [x] Некорректно пересобирается проект при shift+f5 (собирает только актуальные, должен все)
- [x] Исправить и проверить Relicta-Team/ReSDK_A3.vr/issues/284
- [x] ~~Сменить тип у событий роли BasicMob -> Mob. (*Скорее всего меняем только для getEquipment и вызываться он будет только если унаследован от моба внутри*)~~
- [x] Relicta-Team/ReSDK_A3.vr/issues/282
- [x] Relicta-Team/ReSDK_A3.vr/issues/281
- [x] Документация

# Примечания
## Пункт 2.
Выходные порты должны иметь совместимый тип. Нужно проверить в BP какие типы возвращаются при создании префабов, акторов или иных типов объектов. 
### Результат
- Структуры и спавнеры возвращают фактические типы. 
1. Рефакторим структуру, делая её универсальной но убрав порт преобразования (только опция typeset_out) и узел должен быть c port_deletion_allowed
2. Со спавнерами объектов пока думаю... Вероятнее всего придется переделывать classname в полные типы
## Пункт 3.
Под вопросом. Если будем использовать сущность типа выше то это накладывает ограничения, например несоответствие логики взятия обсервера или госта.

**Comment by Yobas** [comment]
Требует исправления
![image](https://github.com/Relicta-Team/ReNodes/assets/35444748/e9afc73e-6892-4bf9-94e9-4efe0b4d7940)

# Исправлено в следующем релизе
